apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: gpu-serving
spec:
  amiFamily: AL2023
  amiSelectorTerms:
    - name: amazon-eks-node-al2023-x86_64-nvidia-1.35-v20260304
      owner: amazon

  role: gpu-inference-karpenter-node

  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: gpu-inference

  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: gpu-inference

  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        deleteOnTermination: true
        encrypted: true
        volumeSize: 120Gi
        volumeType: gp3

  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required

  tags:
    Name: gpu-inference-karpenter-gpu
    workload: gpu
