alertmanager:
  enabled: false

grafana:
  adminPassword: admin
  service:
    type: ClusterIP
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
    datasources:
      enabled: true

prometheus:
  service:
    type: ClusterIP
  prometheusSpec:
    retention: 3d
    scrapeInterval: 15s
    evaluationInterval: 15s
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    podMonitorNamespaceSelector: {}
