prometheus:
  url: http://kube-prometheus-stack-prometheus.monitoring.svc
  port: 9090
  path: ""

rules:
  default: false
  custom:
    - seriesQuery: 'vllm:num_requests_waiting{namespace!="",pod!=""}'
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      name:
        matches: '^vllm:num_requests_waiting$'
        as: 'vllm_requests_waiting'
      metricsQuery: 'max(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>)'
