apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: vllm-metrics
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - app
  selector:
    matchLabels:
      app: vllm-openai
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 15s
